title: Thi-Thao Nguyen
description: Hi there, I'm Thao.
baseurl: "/TaniaJekyll" # the subpath of your site, e.g. /blog
url: "thithaonguyen.github.io" # the base hostname & protocol for your site, e.g. http://example.com

title-separator: "-"

author:
  name: Thi Thao Nguyen
  github: thithaonguyen
  facebook: thao.t.nguyen.68
  email: thithaonguyen1268@gmail.com


# Build settings
timezone: "Brisbane"
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: /:categories/:title
# paginate: 24
# paginate_path: "/thought/page-:num"

# Facebook App ID
# fb_app_id: ""

sass:
  style: compact

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME

plugins:
  - jekyll-feed
